### ISSUE TITLE
What is the MODS size?

### ISSUE THREAD

**Issue by kometa-triatlon** [bborja/mods_evaluation#5]
Hi,

I would like to thank you for your massive contribution. I am only confused with the amount of data made available with MODS dataset.

The paper says:  We present a new diverse maritime evaluation dataset containing approximately 81k stereo images synchronized with an on-board IMU, with over 60k objects annotated.

However, upon download I was only able to find 16350 frames, i.e. 8175 stereo images.

I am wondering, is this only a publicly available evaluation subset of it? Can the rest of the data be accessed?

In the paper you also state that you have merged the MODD1, MODD2 and SMD datasets into a single MODS training
dataset, but it sounds something different to me. Anyway, it results only in 24k images.

**Comment by bborja** [comment]
Hi! Yes, you are correct, the MODS training dataset is a separate thing. In MODS evaluation dataset there are more than 81k stereo image in total. However, out of these 81k+ images, each 10th image was fully annotated (yielding 8.1k images), and this is the subset that you have downloaded. You can use the in-between images for e.g. temporal filtering etc., but evaluation is only done on each 10th image. Please contact @lojzezust or @JonNatanael to acquire full dataset.
